#!/bin/sh

if ! type "wkhtmltopdf" > /dev/null; then
	echo "Please install wkhtmltopdf"
	exit 1
fi

f=$(echo "$1" | iconv -t ascii//TRANSLIT | sed -E s/[^a-zA-Z0-9]+/-/g | sed -E s/^-+\|-+$//g | tr A-Z a-z)
f=${f/https-/}
f=${f/http-/}
wkhtmltopdf $1 $f.pdf
